# This file was generated by the {rix} R package v0.12.4 on 2025-01-06
# with following call:
# >rix::rix(r_ver = "bf689c40d035239a489de5997a4da5352434632e",
#  > r_pkgs = c("tidyverse",
#  > "tidyr",
#  > "purrr",
#  > "furrr",
#  > "gt",
#  > "easystats",
#  > "rlang",
#  > "DHARMa",
#  > "devtools",
#  > "patchwork",
#  > "rmarkdown"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(package_name = "xeredar",
#  > repo_url = "https://github.com/basf/xeredar",
#  > commit = "2b85763"),
#  > tex_pkgs = c("amsmath"),
#  > ide = "rstudio",
#  > project_path = "./vignettes",
#  > overwrite = TRUE)
# It uses nixpkgs' revision bf689c40d035239a489de5997a4da5352434632e for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/bf689c40d035239a489de5997a4da5352434632e.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      devtools
      DHARMa
      easystats
      furrr
      gt
      patchwork
      purrr
      rlang
      rmarkdown
      tidyr
      tidyverse;
  };
 
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "xeredar";
      src = pkgs.fetchgit {
        url = "https://github.com/basf/xeredar";
        rev = "2b85763";
        sha256 = "sha256-Yxbp8Qi3TOXFhdgZ2shRNSuN0gkermY8OEAMVwhIlp8=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          Matrix
          ARTool
          broom
          bslib
          car
          dplyr
          emmeans
          fBasics
          ggplot2
          ggpubr
          gt
          lme4
          magrittr
          MASS
          multcomp
          parameters
          performance
          readxl
          rlang
          shiny
          shinydashboard
          shinyWidgets
          tibble
          tidyr;
      };
    })
   ];
 
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath;
  });
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [ git_archive_pkgs rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs tex system_packages  wrapped_pkgs ];
  
}
