# This file was generated by the {rix} R package v0.12.4 on 2025-01-08
# with following call:
# >rix::rix(r_ver = "6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212",
#  > r_pkgs = c("tidyverse",
#  > "tidyr",
#  > "purrr",
#  > "furrr",
#  > "gt",
#  > "easystats",
#  > "rlang",
#  > "DHARMa",
#  > "devtools",
#  > "patchwork",
#  > "rmarkdown"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(package_name = "xeredar",
#  > repo_url = "https://github.com/basf/xeredar",
#  > commit = "ca1d789"),
#  > tex_pkgs = c("amsmath"),
#  > ide = "rstudio",
#  > project_path = "./vignettes",
#  > overwrite = TRUE)
# It uses nixpkgs' revision 6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212 for reproducibility purposes
# which will install R version 4.4.0.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      devtools
      DHARMa
      easystats
      furrr
      gt
      patchwork
      purrr
      rlang
      rmarkdown
      tidyr
      tidyverse;
  };
 
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "xeredar";
      src = pkgs.fetchgit {
        url = "https://github.com/basf/xeredar";
        rev = "ca1d789";
        sha256 = "sha256-OzTJkNdThqK9lI3IagtBD6MWt27Qo3oIObOCHBN75qA=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          broom
          bslib
          car
          dplyr
          emmeans
          fBasics
          ggplot2
          ggpubr
          lme4
          MASS
          multcomp
          parameters
          performance
          rlang
          tibble
          tidyr
          shiny
          shinydashboard
          shinyWidgets;
      };
    })
   ];
 
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath;
  });
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [ git_archive_pkgs rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs tex system_packages  wrapped_pkgs ];
  
}
